version: '3.8'

services:
  n8n:
    image: carlosov/n8n-ffmpeg:0.0.6-n8n-test
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ~/.n8n:/home/node/.n8n
    restart: unless-stopped
