version: '3.8'

services:
  n8n:
    image: carlosov/n8n-ffmpeg:0.0.13-n8n-puppeteer
    ports:
      - "5678:5678"
      - "443:443"
      - "80:80"
    env_file:
      - .env
    volumes:
      - ~/.n8n:/home/node
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - ~/evolution_redis:/data
    ports:
      - 6379:6379
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    depends_on:
      - redis
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ~/evolution_instances:/evolution/instances